### ISSUE TITLE
why not make this noarch?

### ISSUE THREAD

**Issue by ngam** [conda-forge/deepxde-feedstock#41]
Your pypi wheel is no arch and your package seems like it is pure python.

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by lululxvi** [comment]
Yes, you are right. It is pure python and should be no arch. It is not "no arch", because a long time ago there is some issue in Windows with Python 2.
