### ISSUE TITLE
matplotlib and xorg-x11-server-Xorg

### ISSUE THREAD

**Issue by ngam** [conda-forge/deepxde-feedstock#43]
https://conda-forge.org/docs/maintainer/knowledge_base.html#matplotlib

@lululxvi, do you know if this applies to you at all?

"if you import parts of matplotlib that link to libX11"

I think this is more like for gui stuff, so if you simply plot and save using pyplot, I believe you should be all clear.

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by lululxvi** [comment]
We should be good.
